# Generated by Django 3.1.5 on 2021-01-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hood',
            name='hospital',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hood',
            name='police',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
