# Generated by Django 3.1.5 on 2021-01-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_auto_20210129_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hood',
            name='residents',
            field=models.IntegerField(blank=True),
        ),
    ]
